# Copy this file to ~/Library/Application Support/macos_actions/actions.yml
# and update the script paths to match your environment.

scripts:
  fetch_yesterday_emails:
    type: applescript
    path: "~/ollama/macos_actions/scripts/Fetch_Yesterday_Emails.applescript"
    timeout: 120  
  fetch_weekend_emails:
    type: applescript
    path: "~/ollama/macos_actions/scripts/Fetch_Weekend_Emails.applescript"
    timeout: 120
  unread_last_hour:
    type: applescript
    path: "~/ollama/macos_actions/scripts/Fetch_LastHour_Unread.applescript"
    timeout: 60
  meetings_today:
    type: shell
    path: "~/ollama/macos_actions/scripts/today_events.py"
    timeout: 90
  meetings_today_detail:
    type: shell
    path: "~/ollama/macos_actions/scripts/today_events.py"
    timeout: 90

reports:
  email_digest:
    unread_key: fetch_yesterday_emails
    meetings_key: meetings_today
    new_mail_key: unread_last_hour
